name: Trigger auto deployment for full-stack-try-2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '//**'
    - '.github/workflows/full-stack-try-2-AutoDeployTrigger-1bdd4c94-26c8-4f7e-89d3-146bec95f493.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FULLSTACKTRY2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FULLSTACKTRY2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FULLSTACKTRY2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryl7guu6wehhy5m.azurecr.io
          registryUsername: ${{ secrets.FULLSTACKTRY2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FULLSTACKTRY2_REGISTRY_PASSWORD }}
          containerAppName: full-stack-try-2
          resourceGroup: fullstackappa00a
          imageToBuild: containerregistryl7guu6wehhy5m.azurecr.io/full-stack-try-2:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


